import re
import requests
import base64
from datetime import datetime
from typing import Optional, List
from crewai.tools import tool
from ddgs import DDGS
from bs4 import BeautifulSoup
from models import LotData
from openai import OpenAI


def get_openai_client():
    return OpenAI()

def download_image_as_data_url(url: str) -> str:
    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/122.0.0.0 Safari/537.36"
        )
    }

    r = requests.get(url, headers=headers, timeout=20)
    r.raise_for_status()

    content_type = r.headers.get("Content-Type", "image/jpeg")
    encoded = base64.b64encode(r.content).decode("utf-8")
    return f"data:{content_type};base64,{encoded}"


@tool
def analyze_coin_images(image_urls: List[str]) -> str:
    """Analyze multiple coin images from one lot."""
    client = get_openai_client()

    content = [
        {
            "type": "input_text",
            "text": (
                "These are images from one coin lot. "
                "Use all images together and return a structured assessment of:\n"
                "- visible inscriptions\n"
                "- coin type clues\n"
                "- wear / grade clues\n"
                "- damage / cleaning signs\n"
                "- forgery risk\n"
                "- suspicious authenticity signals\n"
                "- uncertainty\n"
            ),
        }
    ]

    for url in image_urls:
        data_url = download_image_as_data_url(url)
        content.append({
            "type": "input_image",
            "image_url": data_url
        })

    resp = client.responses.create(
        model="gpt-5.1",
        input=[{"role": "user", "content": content}],
    )
    return resp.output_text


@tool("web_search")   
def search_web(query: str) -> str:
    """
    Search information in the internet
    Args:
        query: test for search
    """
    try:
        with DDGS(timeout=10) as ddgs:
            results_iter = ddgs.text(
                query,
                max_results=10,
                backend="duckduckgo",
            )

            results = []
            for r in results_iter:
                results.append(r)
                if len(results) >= 10:
                    break

            if not results:
                return "Nothing was found"

            output = "Found results:\n\n"

            for i, r in enumerate(results, 0):
                output += f"{i}. {r.get('title', '')}\n"
                output += f"   {r.get('body', '')[:200]}...\n"
                output += f"   {r.get('href', '')}\n\n"

            return output
    except Exception as e:
        print(f" Search error: {e}")
        return "Search error"


@tool("current_time")
def get_current_date() -> str:
    """
    Get current time
    """
    now = datetime.now()
    print(f"Current date is {now}")
    return now.strftime("%Y-%m-%d")


@tool("report_generator")
def save_report(data: str, filename: Optional[str]) -> str:
    """
    Save report file
    Args:
        data: Data to store
        filename: Filename name
    """
    if not filename:
        filename = f"report.md"
    
    report_content = f"""
# CrewAI report
**Date:** {datetime.now():%Y-%m-%d %H:%M}

## Not Financial Advice

This project does not provide financial, investment, or trading advice.

The price estimation generated by the system are algorithmic estimates and should not be interpreted as professional advice. Always perform independent research before making financial decisions.

## Content
{data}

---
* CrewAI Multi-Agent System*
    """
    
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(report_content)
    
    print(f"[OK] Report saved: {filename}")
    return f"[OK] Report saved: {filename}"



@tool("violity_lot_validator")
def validate_violity_url(url: str) -> str:
    """
    Validate if the lot URL is from Violity
    Args:
        url: url to auction
    """
    
    if "violity.com" not in url:
        raise ValueError("URL is not a Violity link")
    else:
        return "The lot is from Violity auction"



def extract_lot_id(url: str) -> Optional[str]:
    m = re.search(r"/(\d+)-", url)
    return m.group(1) if m else None


def fetch_lot_page(url: str, timeout: int = 20) -> str:
    """
    Fetch auction page
    Args:
        url: url to auction
        timeout: request timeout
    """
    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/122.0.0.0 Safari/537.36"
        )
    }
    resp = requests.get(url, headers=headers, timeout=timeout)
    resp.raise_for_status()
    return resp.text


def clean_text(value: Optional[str]) -> Optional[str]:
    if value is None:
        return None
    return " ".join(value.split())


def extract_price_after_label(text: str, label: str) -> Optional[float]:
    pattern = rf"{re.escape(label)}.*?([\d\s]+(?:[.,]\d+)?)\s*грн"
    m = re.search(pattern, text, flags=re.IGNORECASE | re.DOTALL)
    if not m:
        return None
    raw = m.group(1).replace(" ", "").replace(",", ".")
    try:
        return float(raw)
    except ValueError:
        return None


def parse_ua_datetime(value: str) -> Optional[datetime]:
    value = value.strip()
    for fmt in ("%d.%m.%Y, %H:%M:%S", "%d.%m.%Y, %H:%M"):
        try:
            return datetime.strptime(value, fmt)
        except ValueError:
            pass
    return None


def extract_added_at(page_text: str) -> Optional[datetime]:
    # first "Додано: 28.02.2026, 13:54"
    m = re.search(r"Додано:\s*(\d{2}\.\d{2}\.\d{4},\s*\d{2}:\d{2})", page_text)
    return parse_ua_datetime(m.group(1)) if m else None


def extract_ends_at(page_text: str) -> Optional[datetime]:
    # "Закінчення 14.03.2026, 13:54:00 +5m"
    m = re.search(r"Закінчення\s*(\d{2}\.\d{2}\.\d{4},\s*\d{2}:\d{2}:\d{2})", page_text)
    if m:
        return parse_ua_datetime(m.group(1))

    # fallback: "Торги завершені 14.03.2026, 13:54:00"
    m = re.search(r"Торги завершені\s*(\d{2}\.\d{2}\.\d{4},\s*\d{2}:\d{2}:\d{2})", page_text)
    if m:
        return parse_ua_datetime(m.group(1))

    return None


def parse_label_value_pairs(soup: BeautifulSoup) -> dict:
    text_lines = [clean_text(x) for x in soup.stripped_strings]
    text_lines = [x for x in text_lines if x]

    wanted_labels = {
        "Метал:": "metal",
        "Матеріал:": "material",
        "Стан:": "condition_text",
        "Реставрація:": "restoration",
        "Дефекти:": "defects",
        "Місцезнаходження:": "location",
        "Оплата:": "payment",
        "Доставка:": "shipping",
        "Опис:": "description",
    }

    result = {}
    for i, line in enumerate(text_lines[:-1]):
        if line in wanted_labels:
            result[wanted_labels[line]] = text_lines[i + 1]
    return result


def extract_seller(page_text: str) -> Optional[str]:
    m = re.search(r"\n([A-Za-z0-9_\-]+)\(\d+(?:\.\d+)?\)\n", page_text)
    return m.group(1) if m else None


def detect_status(page_text: str, ends_at: Optional[datetime], now: Optional[datetime] = None) -> str:
    if now is None:
        now = datetime.now()

    # Main criteria the end date
    if ends_at is not None and ends_at > now:
        return "active"


    sold_markers = [
        "Торги завершені. Лот проданий.",
        "Лот проданий",
        "Вітаємо Вас з покупкою!",
    ]
    closed_markers = [
        "Торги по цьому лоту завершені",
        "Торги завершені",
        "Лот закритий",
    ]

    if any(marker in page_text for marker in sold_markers):
        return "sold"

    if any(marker in page_text for marker in closed_markers):
        return "closed"

    # fallback
    has_current_price = "Поточна ціна" in page_text
    has_bid_action = "Зробити ставку" in page_text
    has_auto_bid = "Автоматичний торг" in page_text
    has_buy_now = "Купити зараз" in page_text

    if has_current_price and (has_bid_action or has_auto_bid or has_buy_now):
        return "active"

    return "unknown"


def extract_images(soup: BeautifulSoup, lot_title: Optional[str]) -> List[str]:
    image_urls = []

    for img in soup.find_all("img", src=True):
        src = img["src"]
        alt = img.get("alt", "")

        if not src:
            continue

        src_lower = src.lower()
        if any(x in src_lower for x in ["logo", "avatar", "icon", "banner", "sprite"]):
            continue

        if lot_title and lot_title[:20].lower() in alt.lower():
            image_urls.append(src)
            continue

        if any(x in src_lower for x in ["/uploads/", "/images/", "/img/"]):
            image_urls.append(src)

    return list(dict.fromkeys(image_urls))


@tool("violity_lot_parser")
def parse_violity_lot(url: str, now: Optional[datetime] = None) -> str:
    """
    Fetch auction page
    Args:
        url: url of the lot
    """
    html = fetch_lot_page(url)
    soup = BeautifulSoup(html, "html.parser")
    page_text = "\n".join(soup.stripped_strings)

    ends_at = extract_ends_at(page_text)
    added_at = extract_added_at(page_text)

    lot = LotData(
        url=url,
        auction_house="Violity",
        lot_id=extract_lot_id(url),
        seller=extract_seller(page_text),
        added_at=added_at,
        ends_at=ends_at,
    )

    h1 = soup.find("h1")
    if h1:
        lot.title = clean_text(h1.get_text())

    lot.status = detect_status(page_text, lot.ends_at, now=now)

    lot.current_price_uah = extract_price_after_label(page_text, "Поточна ціна")
    lot.buy_now_price_uah = (
        extract_price_after_label(page_text, "Купити зараз за")
        or extract_price_after_label(page_text, "Купити зараз")
    )

    if lot.status in {"sold", "closed"}:
        lot.final_price_uah = (
            extract_price_after_label(page_text, "Продано за")
            or extract_price_after_label(page_text, "Фінальна ціна")
            or extract_price_after_label(page_text, "Лот проданий")
            or extract_price_after_label(page_text, "Торги завершені")
        )

    pairs = parse_label_value_pairs(soup)
    for k, v in pairs.items():
        setattr(lot, k, v)

    lot.image_urls = extract_images(soup, lot.title)
    return str(lot)